heading: Brand Applications
slug: brand-applications
order: 7
sections:
  - content:
      - discriminant: intro
        value:
          heading: Brand
      - discriminant: fullWidthImage
        value:
          image: /brand-1.jpg
      - discriminant: fullWidthImage
        value:
          image: /brand-2.jpg
      - discriminant: fullWidthImage
        value:
          image: /brand-3.jpg
      - discriminant: fullWidthImage
        value:
          image: /brand-4.jpg
      - discriminant: intro
        value:
          heading: Website
      - discriminant: fullWidthImage
        value:
          image: /web-2.jpg
      - discriminant: fullWidthImage
        value:
          image: /web-1.jpg
      - discriminant: intro
        value:
          heading: Product
      - discriminant: fullWidthImage
        value:
          image: /product-1.jpg
